### ISSUE TITLE
ResourceConflictException when updating lambda configuration

### ISSUE THREAD

**Issue by fbn-roussel** [lumigo-io/SAR-measure-cold-start#16]
I get this this error in the `loop` step when the lambda configuration is updated and number of invocations is > 1 :

```json
{
  "errorType": "ResourceConflictException",
  "errorMessage": "The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:eu-west-1:xxxxxxxx:function:xxxxxxxxxxxx",
  "trace": [
    "ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:eu-west-1:xxxxxxxx:function:xxxxxxxxxxxx",
    "    at Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)",
    "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
    "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
    "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)",
    "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
    "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
    "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
    "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
    "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)"
  ]
}
```

I don't really get why this happen as we have a for loop with await keywords :

```typescript
	let done = 0;
	for (let i = 0; i < count; i++) {
		await updateEnvVar(functionName, envVars);
		await invoke(functionName, payload);
		done++;

		if (context.getRemainingTimeInMillis() < 10000) {
			return { ...input, count: count - done };
		}
	}
```

A potential fix could be to add retry behavior to the update lambda configuration call.

I will make a PR.

SAR version : 1.4.0.

**Comment by drissamri** [comment]
I've fixed this with the SDK Waiter functionality in https://github.com/lumigo-io/SAR-measure-cold-start/pull/21
